# $OpenBSD: Makefile,v 1.3 2010/07/09 09:37:37 jakemsr Exp $

COMMENT =		rabbit fighting game

V =			rev269
DISTNAME =		lugaru-$V-src
PKGNAME =		lugaru-$V
CATEGORIES=		games
EXTRACT_SUFX =		.tar.bz2

HOMEPAGE =		http://www.wolfire.com/lugaru/
MASTER_SITES =		https://lugaru.googlecode.com/files/

# GPLv2 or later
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_FTP=	Yes

MODULES =		devel/cmake

WANTLIB =		c ogg m pthread vorbis vorbisfile SDL GL GLU ICE SM X11 Xext stdc++ z png openal jpeg

LIB_DEPENDS =		audio/libvorbis \
			devel/sdl \
			graphics/png \
			graphics/jpeg \
			audio/openal

NO_TEST=	Yes
pre-configure:
	cd ${WRKDIST} && mkdir -p build && cd build && cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=${WRKDIST}/build ../ 
do-install:
	cd ${WRKDIST}/build && echo "cd /usr/local/lugaru && lugaru && cd -" > launcher && chmod +x launcher
	${INSTALL_PROGRAM} ${WRKDIST}/build/launcher /usr/local/bin/lugaru

.include <bsd.port.mk>
